Style/PercentQLiterals:
  EnforcedStyle: upper_case_q

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/StringLiteralsInInterpolation:
  EnforcedStyle: double_quotes

Metrics/LineLength:
  Max: 120

Naming/VariableNumber:
  EnforcedStyle: snake_case

Documentation:
  Enabled: false

AllCops:
  Exclude:
    - vendor/bundle/**/*
    - "bin/**/*"
    - "db/**/*"
    - "log/**/*"
    - "tmp/**/*"
    - "**/*.yml"
    - "config.ru"
    - "Gemfile.lock"
    - "Rakefile"
    - "README.md"
